#!/bin/sh

TEST_NO=ps0001
TEST_DESC="struct_C Python-SIMPL unit test"

export PYTHONPATH=$PYTHONPATH:$SIMPL_HOME/modules

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

cd $SIMPL_HOME/python/test/struct_C
python receiver.py &

sleep 1

python sender.py

fcslay RECEIVER

echo "Test finished you can run posttest $TEST_NO for result"
