#! /bin/sh

$SIMPL_HOME/bin/tclSurrogate -n SURRO -p 50000 &

sleep 1

python receiverCcharacter.py &

sleep 1

python senderCcharacter.py

fcslay RECEIVER_C
killall python receiverCcharacter.py 1>/dev/null 2>&1
fcslay SURRO