#!/bin/bash
#
#$Log: runtest,v $
#Revision 1.1  2007/07/24 20:34:25  bobfcsoft
#new file
#
#

TEST_NO=s0007
TEST_DESC="statemachine unit test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test $TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

echo "" | tee -a $OUTFILE
echo "This may take a while to complete ... please wait" | tee -a $OUTFILE
echo "" | tee -a $OUTFILE

cd $SIMPL_HOME/bin
fclogger -n LOGGER > $TEST_DIR/results/junk & 

cd $SIMPL_HOME/softwareICs/statemachine/SM_door/bin
cksum SM_door | tee -a $OUTFILE
SM_door -n STATEMACHINE -a STIM -f $TEST_DIR/data/bob.dat -l LOGGER &

sleep 1

echo "======================================="
echo ""
echo "on a separate console type:"
echo "    auxtest s0007"
echo "to see the trace log file"
echo ""
echo "for help type:"
echo " -> ?"
echo "======================================="

cksum eventStim | tee -a $OUTFILE
eventStim -n STIM -s STATEMACHINE -p $TEST_DIR/data -l LOGGER

fcslay STATEMACHINE
fcslay LOGGER

echo "Test finished you can run posttest $TEST_NO for result"
