#!/bin/bash
#
#$Log: runtest,v $
#Revision 1.1  2007/07/03 18:33:20  bobfcsoft
#new test
#
#
#

TEST_NO=s0003a
TEST_DESC="SIMPL benchmark via sandboxRelay"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test $TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

echo "" | tee -a $OUTFILE
echo "This may take a while to complete ... please wait" | tee -a $OUTFILE
echo "" | tee -a $OUTFILE

cd $SIMPL_HOME/benchmarks/bin
cksum receiver | tee -a $OUTFILE
receiver -n BOBR 

fcslay BOBR
echo "Test finished you can run posttest $TEST_NO for result"
