#!/bin/bash
#
#$Log: setup,v $
#Revision 1.1  2007/07/03 18:33:20  bobfcsoft
#new test
#
#
#

TEST_NO=s0003a
TEST_DESC="SIMPL benchmark via sandboxRelay"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
DATA_DIR=$TEST_DIR/data

OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

#
# bulk of pretest script goes here
#

echo "Test $TEST_NO setup finished"
