#!/bin/sh
#

TEST_NO=ps0009mc
TEST_DESC="Python-SIMPL unit test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/aftershot

echo "preparing results for test#$TEST_NO ... please wait" | tee $OUTFILE
date | tee -a $OUTFILE

#
# You may want to grep log for signatures here
#
echo "======================="		 | tee -a $OUTFILE

cat $TEST_DIR/results/test.out 		 | tee -a $OUTFILE

echo "done preparing results for test#$TEST_NO"
