#!/bin/bash
#
#$Log: whathappened,v $
#Revision 1.1  2008/12/17 15:42:33  bobfcsoft
#new file
#
#

TEST_NO=s0009
TEST_DESC="relay unit test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/aftershot

echo "preparing results for test#$TEST_NO ... please wait" | tee $OUTFILE
date | tee -a $OUTFILE
echo "======================="		 | tee -a $OUTFILE
echo "Here is the test output"		 | tee -a $OUTFILE

#
# You may want to grep log for signatures here
#
echo "======================="		 | tee -a $OUTFILE

vi $TEST_DIR/results/junk

cat $TEST_DIR/results/test.out 		 | tee -a $OUTFILE

echo "done preparing results for test#$TEST_NO"
