#!/bin/bash
#
#
#

TEST_NO=s0013
TEST_DESC="Python unit test with tclSurrogate"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/aftershot

echo "preparing results for test#$TEST_NO ... please wait" | tee $OUTFILE
date | tee -a $OUTFILE
echo ""					| tee -a $OUTFILE
echo "Here is the test puzzle answer"	| tee -a $OUTFILE
cat $TEST_DIR/data/answer_9.dat		| tee -a $OUTFILE
echo ""					| tee -a $OUTFILE
echo "======================="		 | tee -a $OUTFILE
echo "Here is the test output"		 | tee -a $OUTFILE


#
# You may want to grep log for signatures here
#
echo "======================="		 | tee -a $OUTFILE

cat $TEST_DIR/results/test.out 		 | tee -a $OUTFILE

echo "done preparing results for test#$TEST_NO"
