#! /bin/sh

if [ $# -ne 1 ]; then
	echo "Incorrect command line."
	exit
fi

if [ $1 -eq 3 ]
then
	echo "python 3"
	python3 receiverTrig.py &
else
	echo "python 2"
	python receiverTrig.py &
fi

sleep 1

if [ $1 -eq 3 ]
then
	python3 senderTrig.py

else
	python senderTrig.py

fi

fcslay RECEIVER_C