#!/bin/bash
#
#$Log: runtest,v $
#Revision 1.1  2007/07/24 20:34:24  bobfcsoft
#new file
#
#

TEST_NO=s0004
TEST_DESC="polling emitter unit test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test $TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

echo "" | tee -a $OUTFILE
echo "This may take a while to complete ... please wait" | tee -a $OUTFILE
echo "" | tee -a $OUTFILE

cd $SIMPL_HOME/bin
fclogger -n LOGGER > $TEST_DIR/results/junk & 

cd $SIMPL_HOME/softwareICs/pollingEmitter/bin
cksum emitter | tee -a $OUTFILE
emitter -n EMITTER -q QUEUE -f $TEST_DIR/data/bob.dat -l LOGGER &

cksum queueSim | tee -a $OUTFILE
queueSim -n QUEUE -l LOGGER 

fcslay QUEUE
fcslay EMITTER
fcslay LOGGER
echo "Test finished you can run posttest $TEST_NO for result"
