#! /bin/sh

CLASSPATH=../../class
LIBPATH=../../lib

$SIMPL_HOME/bin/tclSurrogate -n SURRO -p 50000 &

sleep 1

java -classpath $CLASSPATH ReceiverSoffset &

sleep 1

java -classpath $CLASSPATH -Djava.library.path=$LIBPATH SenderJoffset

fcslay RECEIVER
fcslay SURRO
