#! /bin/sh

CLASSPATH=../../class
LIBPATH=../../lib

$SIMPL_HOME/bin/tclSurrogate -n SURRO -p 50000 &

sleep 1

java -classpath $CLASSPATH -Djava.library.path=$LIBPATH ReceiverJbinary &

sleep 1

java -classpath $CLASSPATH SenderSbinary

fcslay RECEIVER
fcslay SURRO
