###############################################
#
# Makefile - for cleaning up simpl/lib
#
#$Log: Makefile,v $
#Revision 1.2  2008/11/27 20:32:27  johnfcsoft
#clobber-->clean
#
#
###############################################
#===============================================
# Default targets
# This makefile is only used to clean specific
# files in the simpl/lib directory
#===============================================
clean:\
     title
	@-rm libfctclx.*
	@-rm libsimpl.*
	@-rm libsimpllog.*
	@-rm libsimplmisc.*
	@echo simpl/lib clean

title:
	@echo simpl/lib clean starting
