#!/bin/sh

TEST_NO=ps0005mc
TEST_DESC="mod_C packing/unpacking binary mode unit test"

export PYTHONPATH=$PYTHONPATH:$SIMPL_HOME/modules

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

cd $SIMPL_HOME/python/test/mod_C
python packCtest1.py 

echo "Test finished you can run posttest $TEST_NO for result"
