#!/bin/sh

TEST_NO=js0015
TEST_DESC="Java Ssimpl java-sender/C-receiver binary message test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

cd $SIMPL_HOME/java/test/S

run5 | tee -a $OUTFILE
