#!/bin/sh

TEST_NO=ps0003
TEST_DESC="class_S Python receiver/sender tclSurrogate unit test"

export PYTHONPATH=$PYTHONPATH:$SIMPL_HOME/modules

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

cd $SIMPL_HOME/bin
tclSurrogate -n SURRO -p 50000 &

sleep 1

cd $SIMPL_HOME/python/test/class_S
python receiverCcharacter.py &

python senderCcharacter.py

fcslay RECEIVER_C
killall python receiverCcharacter.py
fcslay SURRO

echo "Test finished you can run posttest $TEST_NO for result"
