#!/bin/sh

# go to the /usr/include directory
cd /usr/include

# look at the various python* directories
for UNITS in 0 1 2 3 4 5 6 7 8 9
do
	for TENTHS in 0 1 2 3 4 5 6 7 8 9
	do
		if [ -d python$UNITS.$TENTHS ]
		then
			VER=$UNITS.$TENTHS
		fi
	done
done

echo $VER
