#!/bin/sh

TEST_NO=js0017
TEST_DESC="Ssimpl java-sender/Jsimpl java-receiver character message test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
DATA_DIR=$TEST_DIR/data

OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

echo "Test $TEST_NO setup finished"
