#!/bin/sh

TEST_NO=js0004
TEST_DESC="Java Ssimpl binary pack/unpack test"

export PYTHONPATH=$PYTHONPATH:$SIMPL_HOME/modules

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

cd $SIMPL_HOME/java/test/S

runSpack1 | tee -a $OUTFILE
