#!/bin/bash
#
#$Log: auxtest,v $
#Revision 1.1  2008/04/24 17:26:50  bobfcsoft
#new file
#
#

TEST_NO=s0008
TEST_DESC="stimulator unit test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test $TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

cd $SIMPL_HOME/softwareICs/stimulator/bin
cksum recvTester | tee -a $OUTFILE
recvTester -n BOBT -s BOBS -p $TEST_DIR/data -f test_001 -l LOGGER

echo "Test finished you can run posttest $TEST_NO for result"
