#!/bin/bash
#
#$Log: setup,v $
#Revision 1.1  2008/04/24 17:26:50  bobfcsoft
#new file
#
#

TEST_NO=s0008
TEST_DESC="stimulator unit test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
DATA_DIR=$TEST_DIR/data

OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

#
# bulk of pretest script goes here
#

echo "Test $TEST_NO setup finished"
