#!/bin/sh

TEST_NO=ps0002ms
TEST_DESC="mod_S C receiver, Python sender, binary mode tclSurrogate unit test"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out

export PYTHONPATH=$PYTHONPATH:$SIMPL_HOME/modules

echo "Starting up test #$TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

cd $SIMPL_HOME/bin
tclSurrogate -n SURRO -p 50000 &

sleep 1

cd $SIMPL_HOME/python/bin
receiver &

cd $SIMPL_HOME/python/test/class_S
python senderCbinary.py

fcslay RECEIVER_B
fcslay SURRO

echo "Test finished you can run posttest $TEST_NO for result"
